version: '3'

services:
  store_backend:
    container_name: cooldevguys-php_monorepo_skeleton-store_backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8030:8030"
      - "9030:9001"
    volumes:
      - .:/applications:delegated
    depends_on:
      - shared_rabbitmq
      - shared_mysql
    command: symfony serve --dir=applications/store/backend/public --port=8030 --force-php-discovery

  dashboard_backend:
    container_name: cooldevguys-php_monorepo_skeleton-dashboard_backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8040:8040"
      - "9040:9001"
    volumes:
      - .:/applications:delegated
    depends_on:
      - shared_rabbitmq
    command: symfony serve --dir=applications/dashboard/backend/public --port=8040 --force-php-discovery

  dashboard_frontend:
    container_name: cooldevguys-php_monorepo_skeleton-dashboard_frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8041:8041"
      - "9041:9001"
    volumes:
      - .:/applications:delegated
    depends_on:
      - shared_rabbitmq
      - dashboard_elasticsearch
      - shared_mysql
    command: symfony serve --dir=applications/dashboard/frontend/public --port=8041 --force-php-discovery

  dashboard_elasticsearch:
    container_name: cooldevguys-php_monorepo_skeleton-products_elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.10
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  shared_mysql:
    container_name: cooldevguys-php_monorepo_skeleton-shared_mysql
    image: mysql:8.0
    ports:
      - 3360:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: [ "CMD", "mysqladmin", "--user=root", "--password=", "--host=127.0.0.1", "ping", "--silent" ]
      interval: 2s
      timeout: 10s
      retries: 10
    command: [ "--default-authentication-plugin=mysql_native_password" ]

  shared_rabbitmq:
    container_name: cooldevguys-php_monorepo_skeleton-shared_rabbitmq
    image: 'rabbitmq:3.7-management'
    restart: unless-stopped
    ports:
      - 5630:5672
      - 8090:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabb1t
